### ISSUE TITLE
Redis base MQ

### ISSUE THREAD

**Issue by wyxloading** [ThreeDotsLabs/watermill#110]
Redis 5.0 release new data type: [Stream](https://redis.io/topics/streams-intro)
That's really powerful mq now.
Besides, redis below version 5, may use data type "list" to implement a mq (i think it should fit software framework that has not much third party dependencies)

**Comment by wyxloading** [comment]
Check this if you guys interested

https://github.com/wyxloading/watermill-redisstream

**Comment by roblaszczak** [comment]
@wyxloading looks very good! :)

Did you have any bigger problems during implementing? I'm asking because we are planning to create contributors guide and I'm not sure what can be missing from your perspective :)

I need more time to look on it, but we would add a link to it to README or if you prefer we can also consider to add it under ThreeDotsLabs/watermill-redisstream (but it's up to you) :)

**Comment by wyxloading** [comment]
Watermill v1.0 is so nice. I only need to set features i want to implement, then run test.  
But `BenchSubscriber` result is kind of confused. It would be nicer if benchmark focus on the subscriber throughput.

> we would add a link to it to README or if you prefer we can also consider to add it under ThreeDotsLabs/watermill-redisstream (but it's up to you) :)

Currently, watermill-redisstream is not production ready. I don't suggest adding to readme at this time. ( I am using in production, please let me check if there is something wrong. )  
Add it under ThreeDotsLabs/watermill-redisstream, that should be nicer :)

**Comment by minghsu0107** [comment]
Hi, I have improved some codes in the watermill-redisstream, such as adding fan-out mode and idle consumer removal.

Check this out if you are interested: https://github.com/minghsu0107/watermill-redistream

**Comment by rwngallego-lm** [comment]
@roblaszczak are you planing to incorporate @minghsu0107 implementation? Would be more than happy to see it "officially" supported

**Comment by m110** [comment]
Continuing the thread in #321 :)
