### ISSUE TITLE
NATS Pub/Sub

### ISSUE THREAD

**Issue by prune998** [ThreeDotsLabs/watermill#12]
https://nats.io/

**Comment by gedw99** [comment]
yes this would be very useful as i prefer pure golang solutions for ease of ops, etc
Also its important it has persistence and so NATS Stream would be needed with one of the included databases.
I think however that NATS Streaming does not allow message topics to be setup at runtime. Not sure..

**Comment by gedw99** [comment]
@roblaszczak 
Have you seen whats happening with knative and cloudevents ?
Its basically a formalised approach to event sourcing / messaging.

Some URLS 
https://github.com/cloudevents/sdk-go
- the linux working groups spec and implementation.
https://github.com/knative/eventing-sources
- Google implemenation

**Comment by roblaszczak** [comment]
@gedw99 I will check, thanks :+1:

**Comment by roblaszczak** [comment]
Added in #19 :tada: @prune998 @gedw99 - I will be appreciated the feedback :)
