### ISSUE TITLE
support rpc over message server

### ISSUE THREAD

**Issue by koolay** [ThreeDotsLabs/watermill#123]
There is a plan for supporting rpc over message?

[nats](https://nats-io.github.io/docs/developer/concepts/reqreply.html)
[rabbitmq](https://www.rabbitmq.com/tutorials/tutorial-six-go.html)

**Comment by m110** [comment]
While it's supported for some Pub/Subs, it seems the semantics are not really compatible with current watermill's interfaces. It could be done by a separate component, like with CQRS. There is a chance that it would work even for other Pub/Subs. I guess we could consider something like that in the future.

**Comment by roblaszczak** [comment]
As Milosz said, currently by design we are not supporting RPC over message by design - our architecture design is totally different and we favor [CQRS](https://watermill.io/docs/cqrs/) for it.
