### ISSUE TITLE
PostgreSQL suport in watermill-sql

### ISSUE THREAD

**Issue by roblaszczak** [ThreeDotsLabs/watermill#127]
https://github.com/ThreeDotsLabs/watermill-sql/ was built using MySQL. 

To make it work with PostgreSQL you probably need to:
- [ ] Implement schema adapter
- [ ] Add PostgreSQL in docker-compose
- [ ] Add tests
- [ ] :champagne:

**Comment by m110** [comment]
Work in progress, mostly ready for review: 
* https://github.com/ThreeDotsLabs/watermill-sql/pull/3
* https://github.com/ThreeDotsLabs/watermill/pull/147
