### ISSUE TITLE
Replace kafka-console-consumer with Mill in examples

### ISSUE THREAD

**Issue by roblaszczak** [ThreeDotsLabs/watermill#130]
Basically, we don't need to have kafka-console-consumer, we have mill instead: https://github.com/ThreeDotsLabs/watermill/tree/master/tools/mill

It would be nice to replace it in all examples.

**Comment by KirylJazzSax** [comment]
Hi! Added mill executable to one of the containers and replaced in examples. If you wanted to do it in other way I am happy to change id.
