### ISSUE TITLE
Middleware per handler

### ISSUE THREAD

**Issue by roblaszczak** [ThreeDotsLabs/watermill#133]
Currently, you are not able to use middleware per handler in "clean way" (you can still manually wrap the handler function, or have separated router).

It would be nice to be able to add middleware per handler.

As a good reference point, you can use chi router: https://github.com/go-chi/chi

**Comment by 0michalsokolowski0** [comment]
I want to work on it

**Comment by 0michalsokolowski0** [comment]
PR: https://github.com/ThreeDotsLabs/watermill/pull/149

**Comment by bkielbasa** [comment]
shouldn't the task be closed? :)

**Comment by roblaszczak** [comment]
Yeah, done ;-)
