### ISSUE TITLE
Logging error when produced Messages and returned error

### ISSUE THREAD

**Issue by roblaszczak** [ThreeDotsLabs/watermill#14]
When error is returned in handler we are discarding produced messages.

```go
	producedMessages, err := handler(msg)
	if err != nil {
		h.logger.Error("Handler returned error", err, nil)
		msg.Nack()
		return
	}

	if err := h.publishProducedMessages(producedMessages, msgFields); err != nil {
		h.logger.Error("Publishing produced messages failed", err, nil)
		msg.Nack()
		return
	}
```

We should log error in this situation.

**Comment by jeroenrinzema** [comment]
Maybe it is a good idea to draw inspiration from the http [`ResponseWriter`](https://golang.org/pkg/net/http/#ResponseWriter). Including a response writer allows the error to be handled instantly instead of it being thrown in a "global" log.

**Comment by roblaszczak** [comment]
obsolete
