### ISSUE TITLE
update sarama version in kafka package

### ISSUE THREAD

**Issue by joy4eg** [ThreeDotsLabs/watermill#172]
Looks like that [PR](https://github.com/Shopify/sarama/pull/1531) was merged a while ago and new version was released - [1.25.0](https://github.com/Shopify/sarama/releases/tag/v1.25.0)

So it's time to upgrade go modules.

Thanks!

**Comment by roblaszczak** [comment]
Done :) My PR to fix some race conditions was included in this release, so probably if somebody had a problem with race check it should work fine now.

Unfortunately, we still have problems with running stress tests in CI (locally it's fine), but I added a separated issue for that: https://github.com/ThreeDotsLabs/watermill/issues/175.
