### ISSUE TITLE
[watermill-amqp] / poison queue is publishing messages to nowhere

### ISSUE THREAD

**Issue by flamedmg** [ThreeDotsLabs/watermill#173]
PosonQueue middleware publishing messages with error without any errrors, but they do not appear anywhere in the rabbitmq. Queue with selected name is not created either.

**Comment by roblaszczak** [comment]
Hello@flamedmg, could you post some example code? Can you also post logs output? Thanks!

**Comment by flamedmg** [comment]
Here is how i create a router:
```
func NewRouter(config RouterConfig, pub message.Publisher, logger logur.Logger) (*message.Router, error) {
	h, err := message.NewRouter(
		message.RouterConfig{
			CloseTimeout: config.CloseTimeout,
		},
		watermilllog.New(logur.WithField(logger, "component", "watermill")),
	)
	if err != nil {
		return nil, errors.WithMessage(err, "failed to create message router")
	}

	retryMiddleware := middleware.Retry{}
	retryMiddleware.MaxRetries = 1
	retryMiddleware.MaxInterval = time.Second * 60

	h.AddMiddleware(
		PoisonQueue(pub),
		retryMiddleware.Middleware,
		middleware.Recoverer,
		middleware.CorrelationID,
	)

	return h, nil
}```
If there is no such a queue in rabbitmq, there is no errors generated and poisoned messages are not delivered anywhere. I solved this by creating topology manually.

**Comment by dwaynelavon** [comment]
I am experiencing this issue as well.

**Comment by roblaszczak** [comment]
Yeah, we had this issue as well. But to be honest I have no idea how to solve that properly. I see 2 options:

1. Publisher should fail if it's publishing to queue that doesn't exist. But it may be tricky to "query" that. It can have performance implications as well.
2. We can pass Subscriber to the middleware and call `SubscribeInitializer.SubscribeInitialize()`. It should create what is needed.  Unfortunately, it's a bit weird that we need to provide subscriber for middleware.


> I solved this by creating topology manually i.e. topology creates poison queue.
That sounds like the best idea, but it's easy to forget :(

@flamedmg  @dwaynelavon  any thoughts on that?

**Comment by farzadmf** [comment]
@flamedmg can I ask you how you implemented your own topology builder?

I'm trying to implement it, but it seems like the `BuildTopology` is not being called; something like this (this is just me testing to see if the functions are called)
```go
type myBuilder struct {
	inner amqp.TopologyBuilder
}

func (m *myBuilder) BuildTopology(
	channel *stread_amqp.Channel,
	queueName string,
	exchangeName string,
	config amqp.Config,
	logger watermill.LoggerAdapter,
) error {
	fmt.Println("In BuildTopology")
	panic("error")
}

func (m myBuilder) ExchangeDeclare(
	channel *stread_amqp.Channel,
	exchangeName string,
	config amqp.Config,
) error {
	fmt.Println("In ExchangeDeclare")
	return m.inner.ExchangeDeclare(
		channel,
		exchangeName,
		config,
	)
}

func newMyBuilder() *myBuilder {
	return &myBuilder{
		inner: &amqp.DefaultTopologyBuilder{},
	}
}
```

and Then I'm setting this in my config:
```go
poisonRabbitCfg := amqp.NewDurablePubSubConfig(
	cfg.RabbitURI,
	func(topic string) string {
		return topic
	},
)
poisonRabbitCfg.TopologyBuilder = newMyBuilder()
```

I see `ExchangeDeclare` being called, but the `BuildTopology` is not being called (as you see I'm even `panic`ing in there to see if it's called, but it's not
