### ISSUE TITLE
Wildcard subscription

### ISSUE THREAD

**Issue by kfreiman** [ThreeDotsLabs/watermill#174]
It would be convinient to have ability subscribe on multiple topics via wildcard character (asterisk)

```go
Subscribe(ctx, "user.*")
```

**Comment by roblaszczak** [comment]
Hello @kfreiman, which Pub/Sub implementation you mean ;) In general, it depends on implementation and library used under the hood but probably for most of them it's not supported by default. 

But if you need to add this I believe that in some cases adding that may be possible.

**Comment by m110** [comment]
Closing in favor of #421 (GoChannel-specific).
