### ISSUE TITLE
repeated consumption by multiple subscribers

### ISSUE THREAD

**Issue by pnpdb** [ThreeDotsLabs/watermill#181]
If multiple subscribers subscribe to the same topic，how can only one subscriber consume this message？thanks

**Comment by roblaszczak** [comment]
Hello @pnpdb, it depends on subscriber implementation :) 
- For Kafka, it depends on the consumer group
- For Google Cloud Pub/Sub it depends on subscription name (you can pass how to generate it to Pub/Sub constructor config)
- For RabbitMQ it depends if you are using queue or pub/sub
- ... etc ;) 

After you will provide a context which implementation are you using, I can probably help more :)

**Comment by pnpdb** [comment]
thank you very much, i have another question, for rabbitmq, how to use pull mod ? for example, i want to pull 100 messages once.

**Comment by m110** [comment]
Hey @pnpdb, you're probably looking for `QosConfig.PrefetchCount`: https://github.com/ThreeDotsLabs/watermill-amqp/blob/master/pkg/amqp/config.go#L449

**Comment by roblaszczak** [comment]
@pnpdb I hope that that answered your question?

Also, the `BulkRead` function may be useful: https://github.com/ThreeDotsLabs/watermill/blob/63b5247f69f7bcadd0846bf0872117a1c4e6d733/message/subscriber/read.go#L10

```
/ BulkRead reads provided amount of messages from the provided channel, until a timeout occurrs or the limit is reached.
func BulkRead(messagesCh <-chan *message.Message, limit int, timeout time.Duration) (receivedMessages message.Messages, all bool) {
```
