### ISSUE TITLE
How to implement event handler for multiple event types?

### ISSUE THREAD

**Issue by umeat** [ThreeDotsLabs/watermill#185]
If you have a read model which is informed by multiple different events, would you just write a handler for each and factor out common code?

**Comment by jiadas** [comment]
Encountered the same problem~

**Comment by roblaszczak** [comment]
Hello @umeat and @jiadas. I covered that already in https://github.com/ThreeDotsLabs/watermill/issues/49 :wink:. 

I'm closing the issue, but please let me know if it's not clear.
