### ISSUE TITLE
watermill-sql subscriber

### ISSUE THREAD

**Issue by B3rs** [ThreeDotsLabs/watermill#188]
Hi,
I have seen that in watermill-sql the schema adapters use a JSON field on database but json is not referenced in any other part of the code (exception made for examples).
This prevents some other use-cases like avro/protobuf serialization in payload. 
Is it possible to change the default type to native binary types like BYTEA for postgres?
This avoids a database check for JSON syntax and gives more freedom for the serialization protocol.
Thanks for all the hard and excellent work, I am loving watermill so far

**Comment by roblaszczak** [comment]
Hello @B3rs, of course it is possible! :) You just need to provide your own implementation of SchemaAdapter (this is the default one: https://github.com/ThreeDotsLabs/watermill-sql/blob/master/pkg/sql/schema_adapter_postgresql.go).
