### ISSUE TITLE
Event Sourcing support

### ISSUE THREAD

**Issue by chongkai** [ThreeDotsLabs/watermill#189]
Hi,

I'm new to watermill and yet fascinated by its design like routers, elegant integration with various pub/subs. While i have read thru doc on cqrs, I don't see a separate doc on event sourcing, so I'm wondering if these are supported already:

> Entity activation/deactivation,

> Entity sharding

> Replay of event logs to rebuild entity state

> Snapshot of entity state

Thanks,
Chongkai

**Comment by roblaszczak** [comment]
Hi @chongkai. There is already the issue for Event Sourcing: https://github.com/ThreeDotsLabs/watermill/issues/8

We will definitely work on that! But please keep in mind, that Event Sourcing is not needed for CQRS :wink:.

(small-advertisement-mode)
It's actually hard, if it will be a part of Watermill. But I'm sure that it will be included in the articles series about [building business applications on our blog](https://threedots.tech/tags/building-business-applications).
(/small-advertisement-mode)
