### ISSUE TITLE
potential concurrency bug in CQRS

### ISSUE THREAD

**Issue by ferbs** [ThreeDotsLabs/watermill#190]
I noticed that Watermill reuses the same CommandHandler instance when processing messages, so the same handler instance might be concurrently processing multiple messages. Each will have unsafe access to any data fields on the handler. 
Consider instantiating a new handler instance for each message processed.

**Comment by roblaszczak** [comment]
This is correct and was not documented. In 03114651e7c2f18970de4263f26d7788958c8067 I added godoc for that. I hope that it is more clear after that :)

Instantiating for every message have multiple problems:
1. if someone cares about performance, he will not have the ability to not create object per message
2. it's harder to provide instruction of how to create object than just ready object ;)

Also, in practice, we had no problem with that. We are just building Handlers that are thread safe. This is how it's also working for routers (for example chi), gRPC server etc. 

For that reason, I think that it will be better to stay with single instance.

I'm doing housekeeping of the issues so if you don't mind I will close that, but if you have something more to add I'm happy to re-open.

Cheers!
