### ISSUE TITLE
Throttle question.

### ISSUE THREAD

**Issue by napei** [ThreeDotsLabs/watermill#191]
Small question about the throttle middleware. Is it throttling the consumption of the queue as a whole, or is it only throttling the consumtion of each consumer.

If I am needing to throttle the consumption of a queue that has multiple consumers, say limit the consumtion to 1000 messages every hour as it calls an external rate-limited API, is this the best way to do it?

**Comment by m110** [comment]
Hey @napei. The throttle works across all handlers in a router, no matter how many consumers you have. So it's a good way to achieve what you need. Just keep in mind that if you add it on router level, all handlers will share the same rate limit.
