### ISSUE TITLE
MessageUUIDHeaderKey should not be a hard requirement.

### ISSUE THREAD

**Issue by Agronis** [ThreeDotsLabs/watermill#192]
Hey team,

The `MessageUUIDHeaderKey` in `watermill-amqp/pkg/amqp/marshaler.go` has a hard constraint on the fact this key exists.

This then requires that any service that is publishing to the service I am attempting to add watermill to, also requires watermill to be the publisher in the upstream service.  This does not feel intended?

I began writing a PR for the code adjustment, but as I continued it unraveled a few questions..

```
func (DefaultMarshaler) Unmarshal(amqpMsg amqp.Delivery) (*message.Message, error) {
	msgUUID, ok := amqpMsg.Headers[MessageUUIDHeaderKey]
	if !ok {
		return nil, errors.Errorf("missing %s header", MessageUUIDHeaderKey)
	}

	msgUUIDStr, ok := msgUUID.(string)
	if !ok {
		return nil, errors.Errorf("message UUID is not a string, but: %#v", msgUUID)
	}

	msg := message.NewMessage(msgUUIDStr, amqpMsg.Body)
	msg.Metadata = make(message.Metadata, len(amqpMsg.Headers)-1) // headers - minus uuid

	for key, value := range amqpMsg.Headers {
		if key == MessageUUIDHeaderKey {
			continue
		}

		msg.Metadata[key], ok = value.(string)
		if !ok {
			return nil, errors.Errorf("metadata %s is not a string, but %#v", key, value)
		}
	}

	return msg, nil
}
```

My proposal would be to add the `ExpectMessageUUIDHeader` to `DefaultMarshaler`

```
	// When false (default), a UUID will be generated if and when the
	// MessageUUIDHeaderKey header is missing from the incoming message.

	// When true, the
	// MessageUUIDHeaderKey becomes a hard requirement
	// in order to successfully unmarshal the message.
	ExpectMessageUUIDHeader bool
```

which then becomes

```
func (d DefaultMarshaler) Unmarshal(amqpMsg amqp.Delivery) (*message.Message, error) {
	msgUUID, ok := amqpMsg.Headers[MessageUUIDHeaderKey]
	if !ok {
		if d.ExpectMessageUUIDHeader {
			return nil, errors.Errorf("missing %s header", MessageUUIDHeaderKey)
		}
	}
```

However, this still allows this message to proceed if it by chance has the header key, but a zero value.

So..?
```
	msgUUIDStr, ok := msgUUID.(string)
	if !ok {
		return nil, errors.Errorf("message UUID is not a string, but: %#v", msgUUID)
	}

	if msgUUIDStr == "" {
		if d.ExpectMessageUUIDHeader {
			return nil, errors.Errorf("message UUID is blank and ExpectMessageUUIDHeader is enabled")
		}
		// No UUID can have unintended downstream effects
		msgUUIDStr = watermill.NewUUID()
	} else {
		_, err := uuid.Parse(msgUUIDStr)
		if err != nil {
			return nil, errors.Errorf("invalid UUID format passed: %s", msgUUIDStr)
		}
	}
```

1. Is this an approach the team even wishes to consider?
2. If the key is present, but zero value, is it desired as the above, return an error or do nothing?
 - The definition of `message.Message` says UUID is not necessary, it is for debugging only, but all of the tests behind the Marshaler interface would lead me to believe otherwise.
3. If the key is present, and not zero value, is there a desire to verify it is of UUID format?

`uuid.Parse` is from `github.com/google/uuid`

Watermill looks like a great utility to simplify the process of PubSub, but the hard requirement that this key be in place forces a dependency across services, which for me is a deal breaker.

Your guidance is appreciated.

Edit: Feel free to dismiss this, as I realize I can just implement my own marshaler.  Just felt that given how straight forward watermill is, this was relevant.

**Comment by roblaszczak** [comment]
After https://github.com/ThreeDotsLabs/watermill-amqp/pull/4 message UUID is not required.
