### ISSUE TITLE
Add kafkaMsg.Key into msg context

### ISSUE THREAD

**Issue by LihuaWu** [ThreeDotsLabs/watermill#195]
Currently, there are 3 types of data provided in the kafkaMsg context which are partition number, offset and timestamp of the message.
In my case, I will need kafkaMsg's key field to filter out some messages.

Would it be better if some method like `MessageKeyFromCtx` and  `setMessageKeyToCtx` could be provided to use?

Thanks for your time and best regards.

**Comment by roblaszczak** [comment]
Hello @LihuaWu it sounds like an idea: feel free to add it to the DefaultMarshaler implementation and post PR!

Another way without posting PR is implementing your own Marshaler that will put it to context for example :)

**Comment by LihuaWu** [comment]
Hi @roblaszczak 
I choose to implement my own Unmarshaler since it will be more flexible.
Thanks for your help!

**Comment by roblaszczak** [comment]
Good to hear that, this is the reason why we are allowing to replace marshaler :)

**Comment by smoya** [comment]
@roblaszczak Would you accept a PR adding the changes requested in this issue? I think this use case is very valid and having to rewrite the marshaler because of this is not ideal.

**Comment by roblaszczak** [comment]
Hey @smoya, I'd be happy to accept such PR :)
