### ISSUE TITLE
can add Subscriber.ServeHTTP(w http.ResponseWriter, r *http.Request)  in the watermill-http

### ISSUE THREAD

**Issue by runner-mei** [ThreeDotsLabs/watermill#197]
I need integration it with my http server.
So need ServeHTTP()

like this:
```` go
func (s *Subscriber) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	return s.server.Handler.ServeHTTP(w, r)
}
````

**Comment by roblaszczak** [comment]
Hello, you can always extend subscriber by using composition, but I will anyway recommend just call whatever you need from a subscriber in an HTTP handler function to avoid coupling :wink:
