### ISSUE TITLE
Add context to the message

### ISSUE THREAD

**Issue by sagikazarmark** [ThreeDotsLabs/watermill#21]
It might be a good idea to add a `context.Context` to the message (just like in case of `http.Request`) to allow passing information through API boundaries. This could be a way to implement distributed tracing for example.

**Comment by roblaszczak** [comment]
Hello, message already has something that can be used as a context: metadata.

It is also a middleware which can be used for distributed tracing: https://github.com/ThreeDotsLabs/watermill/blob/master/message/router/middleware/correlation.go

Does it meet your requirements? :)

**Comment by sagikazarmark** [comment]
Yeah, I know it has metadata, but it cannot accept a `context.Context` since it only supports string metadata.

As for distributed tracing: in simple cases and for logging a correlation ID might be enough, but in a distributed system which uses a more sophisticated tracing mechanism (eg. OpenTracing or OpenCensus) it may not be enough.

Ideally the distributed tracing middleware would extract the serialized tracing information (which in this case is more than just a correlation ID) from the metadata and attach the tracing spans to the context of the message. That way all the middlewares and handlers can receive the same context and record tracing information.

To do the same thing currently, you have to extract the tracing information in each and every middleware/handler. `context.Context` is the defacto solution for this kind of job.

There is one question though: context is immutable and in most cases where context is involved some kind of message passing, adding something to the context requires creating a new message. In case of `http.Request` it is just a copy of the message, but in this library there are mutexes involved as well, so I'm not 100% sure how easy it would be to implement context support.

**Comment by roblaszczak** [comment]
Lengyel, magyar – két jó barát, so added in :tada: #21

**Comment by sagikazarmark** [comment]
WOW, nice 🙂 Thanks a lot!
