### ISSUE TITLE
 Consumers happen to get stuck in a rebalance state due to call group.Close() improperly

### ISSUE THREAD

**Issue by LihuaWu** [ThreeDotsLabs/watermill#210]
**Issue:  Consumers happen to get stuck in a rebalance state due to call group.Close() improperly**

**Module: 	"github.com/ThreeDotsLabs/watermill-kafka/v2/pkg/kafka" v2.2.0**

**go version: 1.14.4**  

**What did you do?**
start more than 2 consumers in a consumer group to consume a topic with 64 partitions.

**What did you expect to see?**
each consumer will consume half partitions data properly.

**What did you see instead?**
Each consumer repeatedly restarts without consuming messages, and this case can be reproduced steadily.
detail log as follows:
[log.txt](https://github.com/ThreeDotsLabs/watermill/files/5594991/log.txt)

**Possible cause**

In https://github.com/ThreeDotsLabs/watermill-kafka/blob/master/pkg/kafka/subscriber.go#L292,
group.Consume() returns with no err due to consumer member change,  

1. group.Close() should not be called since there is no error and the current member still wants to process some partitions' s messages.

2. instead, should continue call group.Consume() to get the new topic partitions claims and consume messages afterward.
3. Besides, according to the official example of the sarama library, https://github.com/Shopify/sarama/blob/master/examples/consumergroup/main.go#L102, group.Consume() should be called in an infinite loop.

Could you please help check the issue, thanks and best regards!

**Comment by LihuaWu** [comment]
@roblaszczak

**Comment by roblaszczak** [comment]
Hello @LihuaWu, I prepared PR that should fix that issue: https://github.com/ThreeDotsLabs/watermill-kafka/pull/12

cc @m110

**Comment by LihuaWu** [comment]
got it, thanks @roblaszczak

**Comment by roblaszczak** [comment]
The change was merged and released :)
