### ISSUE TITLE
Metrics router handler

### ISSUE THREAD

**Issue by xyluet** [ThreeDotsLabs/watermill#211]
https://github.com/ThreeDotsLabs/watermill/blob/eacc162bdedd7a461e4b1b2c96ef8ab87aa902d6/components/metrics/http.go#L20-L38

1. Whats the point of router if you pass promhttp handler to server?
2. Also server `ListenAndServe()` always returns a non nil error

**Comment by checkmunza** [comment]
Why did you close this issue?
