### ISSUE TITLE
GCP PubSub | Subscription linked to a topic from another project

### ISSUE THREAD

**Issue by medinae** [ThreeDotsLabs/watermill#233]
Trying to execute a Subscriber linked to a subscription - which is linked to a topic from a different project -  lead to an error =>

```
{"level":"fatal","error":"cannot subscribe topic corp.order_event: topic of existing sub: projects/othercorp/topics/something; expecting: projects/corp/topics/something else: requested subscription already exists, but for other topic than expected","time":"2021-06-23T13:36:28Z","message":"Impossible to run watermill router"}
```

The error is returned here https://github.com/ThreeDotsLabs/watermill-googlecloud/blob/master/pkg/googlecloud/subscriber.go#L430

Do you guys know why this condition/check exists ?

**Comment by roblaszczak** [comment]
Fixed with https://github.com/ThreeDotsLabs/watermill-googlecloud/pull/15
