### ISSUE TITLE
[watermill-amqp] router multiple handlers on the same topic

### ISSUE THREAD

**Issue by farzadmf** [ThreeDotsLabs/watermill#237]
Hi, I'm using a router and I'm wondering if there's a way to add more than one handler listening on the same RabbitMQ "topic".

I have something like this:
```go
// ...

subscriber, _ := amqp.NewSubcriber(config, logger)
publisher, _ := amqp.NewPublisher(config, logger)

router.AddHandler(
  "handler1"
  "src",
  subscriber,
  "dest",
  publisher,
  func(msg *message.Message) ([]*message.Message, error) { /* do something */},
)

router.AddNoPublishHandler(
  "handler2"
  "src",
  subscriber,
  func(msg *message.Message) error { /* do something else */ },
)
```

But the issue I have is that it's either/or with the handlers; if a message is picked up by `handler1`, it won't be picked up be `handler2` and vice versa

**Comment by m110** [comment]
Hey! It seems you use a config that makes the handlers behave like they're in the same consumer group. See the docs: https://watermill.io/pubsubs/amqp/#amqp-consumer-groups

**Comment by farzadmf** [comment]
Thank you @m110 , actually I _was_ looking at that, but it seems that it's using the "lower level" system (as mentioned in the docs):
> Publishers and Subscribers are rather low-level parts of Watermill

So, I was having problems with adopting that example to work with the higher abstraction level of a router
