### ISSUE TITLE
Official RabbitMQ library

### ISSUE THREAD

**Issue by sagikazarmark** [ThreeDotsLabs/watermill#239]
FYI this is a thing now https://github.com/rabbitmq/amqp091-go

**Comment by prochac** [comment]
Did someone try with `replace` directive in their `go.mod`?
The official one expects API changes though.
https://github.com/rabbitmq/amqp091-go#project-maturity

**Comment by AlexCuse** [comment]
The current latest version doesn't seem to have any breaking changes, seems like it makes sense to use that to me.
