### ISSUE TITLE
how to use cqrs in realworld?

### ISSUE THREAD

**Issue by xtay315** [ThreeDotsLabs/watermill#244]
where can i get   replay for my client?

**Comment by boreq** [comment]
In the CQRS model the commands drive certain actions within your application and the responses produced as a result of those actions are sent back to the callers using events. Therefore if a producer of commands wants to react to their results then that producer should subscribe to the events produced as a result of executing those commands.

That is the best answer I can give you to such a general question.

I think it may make sense to improve the documentation around the CQRS component. I will look into doing that.
