### ISSUE TITLE
Add context.Context for message.HandlerFunc

### ISSUE THREAD

**Issue by rizalgowandy** [ThreeDotsLabs/watermill#250]
Basically context is a great tools for a lot of things, making it as first parameter make sense.
This way we can inject something on the message.Middleware e.g creating a distributed tracing span inside.

From
```
type HandlerFunc func(msg *Message) ([]*Message, error)
```

To
```
type HandlerFunc func(ctx context.Context, msg *Message) ([]*Message, error)
```

**Comment by checkmunza** [comment]
I think we can inject it by using this method `Message.SetContext` .

**Comment by m110** [comment]
Yes, you can use `msg.Context()` and `msg.SetContext()` for passing the `ctx`. Does that do what you need?

**Comment by rizalgowandy** [comment]
Ah I see, that's exactly what I need.
