### ISSUE TITLE
[watermill-amqp] Use AMQP CorrelationId if watermill message ID header not set

### ISSUE THREAD

**Issue by AlexCuse** [ThreeDotsLabs/watermill#265]
I have this implemented in a custom marshaler now but wondering if it makes sense to push back upstream - when we are integrating with legacy services we find it useful to use the correlation ID as the message ID when first brought into watermill - from there they get sent on headers to subsequent services and work normally.

Its a simple change if it would make sense for other users.

**Comment by roblaszczak** [comment]
Hey, I think that it may be useful option :+1:
