### ISSUE TITLE
Protobuf binding for message.Message?

### ISSUE THREAD

**Issue by AlexCuse** [ThreeDotsLabs/watermill#273]
I find myself thinking about adding a protobuf marshaler to watermill-jetstream and wondering if it would make sense to include the contract definitions and generated files in watermill itself.

**Comment by roblaszczak** [comment]
Hey @AlexCuse, can you elaborate a bit more on how do you understand "protobuf marshaler" in that context?

**Comment by AlexCuse** [comment]
Id like to try using protobuf for the actual transport encoding of watermill messages to see if it's "worth it" from a performance perspective.  Likely have a better idea later this week if it's worth pursuing further but was thinking making the contract part of the `message` package could make sense.

**Comment by AlexCuse** [comment]
https://github.com/AlexCuse/watermill-jetstream/commit/a09d68c4ed25727064047a715815f48e5e213aef

The stuff in the `wmpb` package there is what I was thinking of.
