### ISSUE TITLE
Checking for argument == nil wont work for interfaces

### ISSUE THREAD

**Issue by dubyte** [ThreeDotsLabs/watermill#286]
When passing a nil DB the code that checks the db == nill is false because the beginner is an interface so the nil DB satisfies the interface but is nil.  See this link for reference. https://glucn.medium.com/golang-an-interface-holding-a-nil-value-is-not-nil-bb151f472cc7

```go

func NewSubscriber(db beginner, config SubscriberConfig, logger watermill.LoggerAdapter) (*Subscriber, error) {
	if db == nil { // <- this is always false even if we sent a nil db
		return nil, errors.New("db is nil")
	}

```

So in other words there is an assumption that we are caching the case of receiving a nil value and returning an error but db == nill return false in all cases.

The next page explores some ways to check that an interface is nil:
https://mangatmodi.medium.com/go-check-nil-interface-the-right-way-d142776edef1

**Comment by thpk** [comment]
In those examples the function definition calls for an empty interface. That is not the case in the NewSubscriber function.

**Comment by dubyte** [comment]
could you please give an example where NewSubscriber returns error:

**Comment by thpk** [comment]
The trivial example would throw that error:
```
_, err := sql.NewSubscriber(nil, sql.SubscriberConfig{}, nil)
fmt.Println(err)
```

any initialized value of _db_ wouldn't throw this error of course. This error check prevents panics in setup.

**Comment by dubyte** [comment]
First at all thanks for your time. Is really appreciated

The thing is nil can not be passed because it won't compile, and in the moment you are sending a nil value of type  begginer. The condition if db == nil does not evaluate as true.

so imagine unit test scenario is not possible to that NewSuscriber returns: errors.New("db is nil")

please try to get db is nil error in a snippet.

Thanks

**Comment by thpk** [comment]
Have you tried the snippet above? It does work perfectly here.
I suggest you clone the repository and add the the file subscriber_test.go:

```
package sql

import (
	"fmt"
	"testing"
)

func TestSubscriberNil(t *testing.T) {
	_, err := NewSubscriber(nil, SubscriberConfig{}, nil)
	fmt.Println(err)
}
```
