### ISSUE TITLE
Create an awesome watermill repository

### ISSUE THREAD

**Issue by sagikazarmark** [ThreeDotsLabs/watermill#293]
Would be nice to have a curated list of third-party libraries written for Watermill.

For example I was looking for a Zap adapter for the logger and found this after some searching: https://github.com/garsue/watermillzap

But my first instinct was to look around in this repo and the org, so I would have found it sooner there.

**Comment by m110** [comment]
Here it is :) https://watermill.io/docs/awesome/

**Comment by sagikazarmark** [comment]
Awesome!
