### ISSUE TITLE
http router webhooks haven't protection

### ISSUE THREAD

**Issue by IgorDePaula** [ThreeDotsLabs/watermill#294]
http router webhooks haven't protection and not returns error to http client.

**Comment by m110** [comment]
@IgorDePaula Please provide more information, it's not clear what the issue is.

**Comment by IgorDePaula** [comment]
@m110 Sorry, I means, One protection form like protected routes with jwt, or another token authorization form in http router webhook. Without this protection anyone can access the routes and use it.

**Comment by IgorDePaula** [comment]
@m110 ?

**Comment by m110** [comment]
@IgorDePaula The subscriber config allows you to pass a custom Router. You can add an authentication middleware on the Router level to use any auth you need.

**Comment by IgorDePaula** [comment]
@m110  Ok, I'll try. Thank you very much.
