### ISSUE TITLE
RabbitMQ (AMQP) Pub/Sub

### ISSUE THREAD

**Issue by roblaszczak** [ThreeDotsLabs/watermill#3]

**Comment by mrkaspa** [comment]
@roblaszczak what is the progress on this?

**Comment by roblaszczak** [comment]
Nothing was done yet. It will be great if you would like to help with this :) It's already a short guide, which should guide you on how to implement own Pub/Sub: https://watermill.io/docs/pub-sub-implementing/
You should also take a look for some existing implementations of Pub/Subs, for example NATS: https://github.com/ThreeDotsLabs/watermill/blob/master/message/infrastructure/nats/subscriber.go

Probably something is missing, in this case, feel free to hit me on the [gophers slack](https://gophers.slack.com/): [invite here](https://gophersinvite.herokuapp.com/), I would be happy to help.

**Comment by roblaszczak** [comment]
added in PR #33
