### ISSUE TITLE
Problem with Subscriber.Subscribe and goroutine leaks.

### ISSUE THREAD

**Issue by hristobojilov** [ThreeDotsLabs/watermill#307]
When _router.Close()_ is invoked:

-  all running subscribers are notified asynchronously
- _router.Close()_ doesn't wait until _func (h *handler) handleClose(ctx context.Context_) is complete.

The result is that some go routines created by _Subscriber.Subscribe_ are still running for some time after the router is closed. This synchronization problem causes some of our tests to crash.

Please have a look at message/router.go to find to corresponding code.

**Comment by m110** [comment]
This should be fixed now with #304 
See also #235
