### ISSUE TITLE
Are there any popular opensource projects that use this repo?

### ISSUE THREAD

**Issue by drinktee** [ThreeDotsLabs/watermill#308]
Hello , as I want to use this repo in my company's projects. Are there any popular opensource projects that use this repo?
So that I can learn some real-production code about how they use this repo.

**Comment by flowck** [comment]
- 2.6k ⭐️ https://github.com/devtron-labs/devtron
- 1.5k ⭐️ https://github.com/banzaicloud/pipeline
- 1.3k ⭐️ https://github.com/sagikazarmark/modern-go-application
- 499 ⭐️ https://github.com/formancehq/ledger 
- 189 ⭐️ https://github.com/insolar/insolar
- 164 ⭐️ https://github.com/go-vikunja/api
- 106 ⭐️ https://github.com/blackducksoftware/synopsys-detect
- 69 ⭐️ https://github.com/sagikazarmark/mga
- 44  ⭐️ https://github.com/asyncapi/event-gateway
- 25 ⭐️ https://github.com/trustbloc/orb


Source: https://github.com/ThreeDotsLabs/watermill/network/dependents

**Comment by m110** [comment]
Thank you @flowck 🤗
