### ISSUE TITLE
Officially support Redis Pub/Sub

### ISSUE THREAD

**Issue by minghsu0107** [ThreeDotsLabs/watermill#321]
Hi, I have implemented a Redis-based Pub/Sub using Redis Stream last year: https://github.com/minghsu0107/watermill-redisstream (refer to https://github.com/ThreeDotsLabs/watermill/issues/110#issuecomment-1025116775)

I would happily see this implementation officially incorporated under the Watermill organization. I am glad to contribute to this project, thanks!

**Comment by m110** [comment]
Hey @minghsu0107! Thank you for the contribution! We'll review it and will be in touch. :)

**Comment by minghsu0107** [comment]
> Hey @minghsu0107! Thank you for the contribution! We'll review it and will be in touch. :)

Thanks a lot!

**Comment by m110** [comment]
Hey @minghsu0107, here are some thoughts and tips from me after going over the repository.

Let me know what you think and if you need any help implementing changes. :)

Thank you once again for contributing!

- General
	- Consider consistent naming for both package and module names. I see two options:
		- `watermill-redisstream` and `pkg/redisstream`
		- `watermill-redis` and `pkg/redis`
	- We would need to release a semantic version, like `v0.1.0` (or whatever fits)
- Dependencies
	- Let's bump watermill to the latest RC version
	- `github.com/go-redis/redis` mentions you need to use `v9` with Redis 7. Should we support both 6 and 7, or just indicate that Redis 6 is supported for now?
	- `github.com/renstrom/shortuuid` - you can use `watermill.NewShortUUID()`
- Subscriber
	- For consistency with other Pub/Subs, all arguments in the constructor would be moved to the  `Config` struct. This allows us to extend it without breaking changes to the API.
	- `ctx` shouldn't be needed in the constructor, as there's one passed to `Subscribe`.
	- The config should check if the passed Redis client and unmarshaler are not empty.
	- It seems `DefaultBlockTime` and `DefaultClaimInterval` can't be overridden by the config now. Would it make sense to add them?
	- It’s a good practice to return concrete implementation instead of interfaces, so `NewSubscriber` should return `*Subscriber`, not `message.Subscriber` (applies to the `Publisher` as well).
	- [https://github.com/minghsu0107/watermill-redistream/blob/e4094940867dd980d8fd889acc1675abecfbbd93/pkg/redis/subscriber.go#L114](https://github.com/minghsu0107/watermill-redistream/blob/e4094940867dd980d8fd889acc1675abecfbbd93/pkg/redis/subscriber.go#L114) - it seems the customer ID is generated the second time here
	- In `Close()` you may want to use a mutex lock, as a race condition could close the channel twice and panic: [https://github.com/minghsu0107/watermill-redistream/blob/e4094940867dd980d8fd889acc1675abecfbbd93/pkg/redis/subscriber.go#L396](https://github.com/minghsu0107/watermill-redistream/blob/e4094940867dd980d8fd889acc1675abecfbbd93/pkg/redis/subscriber.go#L396)
- Publisher
	- Similarly to the subscriber, let’s move arguments from the constructor to the config.
	- Why `Close` doesn't close the Redis client?
- Tests
	- Consider if you need the global client or can the `redisClient` function just return a new client every time.
	- What’s wrong with `RestartServiceCommand`?
	- Instead of sleeps, you might want to use `require.Eventually`: [https://github.com/minghsu0107/watermill-redistream/blob/e4094940867dd980d8fd889acc1675abecfbbd93/pkg/redis/pubsub_test.go#L182](https://github.com/minghsu0107/watermill-redistream/blob/e4094940867dd980d8fd889acc1675abecfbbd93/pkg/redis/pubsub_test.go#L182)
	- We now have consistent GitHub actions workflows across all repositories, you could use them as well. It would also be good to introduce a docker-compose file instead of running the Redis instance on the CI to make local testing consistent with the pipelines.
