### ISSUE TITLE
Multiple subscribers/handlers for a single topic?

### ISSUE THREAD

**Issue by ivaaaan** [ThreeDotsLabs/watermill#361]
Hi. I want to add multiple handlers for a single topic in Google Cloud Pub/Sub, e.g: 

```go
router.AddNoPublisherHandler("handler1", "event", subscriber, func(m *message.Message) error {
    return nil
})
router.AddNoPublisherHandler("handler2", "event", subscriber, func(m *message.Message) error {
    return nil
})
```

As I understand, I will need multiple `Subscriber` instances for that? Or maybe is there a way to do it with router?

**Comment by m110** [comment]
Hey @ivaaaan, you will need two subscribers if you want one subscription per handler.

You can take a look at the CQRS component if you need more handlers, it provides higher-level API for this.

Also, #356 addresses this to have an API easier to use with multiple subscribers.

**Comment by ivaaaan** [comment]
Thanks @m110, CQRS example looks amazing :)
