### ISSUE TITLE
[watermill-kafka] use github.com/IBM/sarama

### ISSUE THREAD

**Issue by jens1205** [ThreeDotsLabs/watermill#388]
The go.mod still says: `require github.com/Shopify/sarama v1.38.0`

The sarama lib is now available under https://github.com/IBM/sarama, this should be reflected in the go.mod (although there is some forwarding from https://github.com/shopify/sarama to  https://github.com/IBM/sarama)

**Comment by d4nyll** [comment]
`otelsarama` would also need to be replaced as it is [deprecated](https://github.com/open-telemetry/opentelemetry-go-contrib/pull/4099). The most 'popular' (only?) replacement is [dnwe/otelsarama](https://github.com/dnwe/otelsarama). See also https://github.com/IBM/sarama/issues/2510.

**Comment by henrik-olund-wcar** [comment]
I also want this.
