### ISSUE TITLE
Skip First Publisher in Router

### ISSUE THREAD

**Issue by luabagg** [ThreeDotsLabs/watermill#399]
I'm currently developing a Webhook provider which reads the message from Kafka and then proceeds to make the HTTP Request.

The problem is that I need to get the callback URL from the message metadata. My current solution is this using a "dummy publisher":

![image](https://github.com/ThreeDotsLabs/watermill/assets/56180440/921b926d-627e-4df6-9e4c-6f5cf978f89a)

It does not seems appropriate though. Any ideas if there's a better way?
I tried setting the publisher nil, using the NoPublishHandler, etc

**Comment by m110** [comment]
Hey, can you describe a bit more what you're trying to accomplish with the metadata?

**Comment by luabagg** [comment]
I don't know if it is really a good idea, but this is my case:

- I didn't want to define the HTTP publisher topic statically, so I was using the "callbackUrlHeader" (from the Kafka message) to get the HTTP topic.
- In this case, the callbackUrlHeader is first defined by the API caller.

My current flow:
![Filepoint drawio](https://github.com/ThreeDotsLabs/watermill/assets/56180440/de413d75-7417-4e0c-bb4b-e1828cb398e8)

**Comment by luabagg** [comment]
@m110  I just realized why this is such a bad idea and not useful at all... But thanks for your response!
