### ISSUE TITLE
Is it possible to get google pubsub server generated unique message-id?

### ISSUE THREAD

**Issue by arthurspa** [ThreeDotsLabs/watermill#430]
Context: 
I have open an investigation ticket towards google cloud support team for some missing messages sometimes and they asked me the published [messageId](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcloud.google.com%2Fpubsub%2Fdocs%2Freference%2Frest%2Fv1%2FPubsubMessage%23%3A~%3Atext%3Dcount%2522%253A%2520%25223%2522%2520%257D.-%2CmessageId%2C-string&data=05%7C02%7Carthur.silva%40ericsson.com%7C72a13f3078394bed834a08dc54b726e6%7C92e84cebfbfd47abbe52080c6b87953f%7C0%7C0%7C638478392810367867%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=IyKLgLpwJqKiP10dBtktMHVAI3Ftg4D9CGA2upm3gTg%3D&reserved=0).

Initially I gave them them watermill UUID, but they said that was not valid. Indeed, when I inspected watermill-googlecloud code I saw that watermill discards the server generated message id. 

Here's the except:
https://github.com/ThreeDotsLabs/watermill-googlecloud/blob/master/pkg/googlecloud/publisher.go#L166

Is there any way currently to get ahold of this server generated message id somehow?

**Comment by Sankalp951** [comment]
Hi @arthurspa,

It appears that Watermill doesn't generate server-generated message IDs directly. However, you can capture them by either modifying the publish method to log the IDs before returning or by retrieving them directly from the Pub/Sub API.

Hope this helps!

Thank you,
Sankalp

**Comment by arthurspa** [comment]
Hi @Sankalp951 ,

I'm actually interested in getting ahold of the value. In that case, would I have to implement my own "googlecloud" pkg? Or do you know if there is a way to do it using the existing googlecloud pkg?

**Comment by arthurspa** [comment]
Fixed in https://github.com/ThreeDotsLabs/watermill-googlecloud/pull/31
