### ISSUE TITLE
[watermill-http] Custom HTTP response status

### ISSUE THREAD

**Issue by thejoeejoee** [ThreeDotsLabs/watermill#449]
Currently, HTTP subscriber doesn't allow to specify custom HTTP status for the response.

It would be practical to have possibility to change the response status code for specific subscribed message. Only `HTTP 200/400/500` are now returned.

**Comment by thejoeejoee** [comment]
I'm proposing the implementation:

* http: https://github.com/ThreeDotsLabs/watermill-http/pull/14
* docs: https://github.com/ThreeDotsLabs/watermill/pull/450

**Comment by m110** [comment]
Thank you @thejoeejoee, this has been released as v2.3.0! 🎉
