### ISSUE TITLE
HelloGitHub Badge

### ISSUE THREAD

**Issue by 521xueweihan** [ThreeDotsLabs/watermill#456]
<img width="707" alt="image" src="https://github.com/ThreeDotsLabs/watermill/assets/8255800/f17381b5-8d48-4bb0-9f85-ee0dc38ecb50">

🎉 Congratulations! Your [project](https://hellogithub.com/repository/46c93d0596ff41f4b281a7e25b08f9d7) has been featured and recommended by the HelloGitHub community. We invite you to join the HelloGitHub Badge Program. Joining will grant you the following privileges:

- **Community Recognition**: The badge indicates that your project has successfully passed the HelloGitHub community's stringent selection and recommendation process.
- **Increased Exposure**: Displaying the badge will draw more traffic to your project, attracting additional users and contributors.
- **Enhanced Interaction**: Users can quickly understand your project through the badge and engage with it (like, comment, bookmark).
- **Feedback Collection**: Gather genuine feedback from a broad user base, aiding in the continuous improvement of your project.
- **Special Identification**: Once verified, your comments will feature a distinctive mark and be prioritized for pinning.

📌 [Click here](https://hellogithub.com/repository/46c93d0596ff41f4b281a7e25b08f9d7/embed) to wear the badge and join the HelloGitHub Badge Program, allowing your open-source project to shine even brighter.

---

**HelloGitHub** is a community focused on discovering, sharing, and promoting open-source projects. Since its inception in 2016, it has grown from a monthly newsletter into a dynamic community with over **10,000** users. Our footprint extends across multiple content platforms, earning the trust and support of **500,000** fans worldwide.

**Comment by m110** [comment]
Thank you.
