### ISSUE TITLE
Clarification for reading multiple events

### ISSUE THREAD

**Issue by delaneyj** [ThreeDotsLabs/watermill#49]
In the [docs](https://watermill.io/docs/cqrs/#building-a-read-model-with-the-event-handler) `BookingsFinancialReport` is only listening for `RoomBooked` however what if it needed to listen to multiple event types to form the read model.  

My guess is you'd have to have a composite of struct each listening for a single event type.  Wanted to avoid boilerplate but just making sure before moving forward.

**Comment by roblaszczak** [comment]
> My guess is you'd have to have a composite of struct each listening for a single event type.
Correct. In this situation, I will suggest to not put any logic to `Handle()` but just call another service which will be the same for both.

**Comment by Dionid** [comment]
@delaneyj Have you find a way that satisfied your request?
@roblaszczak Can you write example, please?

**Comment by roblaszczak** [comment]
example:
```
type readModelBuilder interface {
	buildBookingsReadModel(guestName string) error
}

type BookingsFinancialReport struct {
	readModelBuilder readModelBuilder
}

func (b BookingsFinancialReport) HandlerName() string {
	// this name is passed to EventsSubscriberConstructor and used to generate queue name
	return "BookingsFinancialReport"
}

func (BookingsFinancialReport) NewEvent() interface{} {
	return &RoomBooked{}
}

func (b *BookingsFinancialReport) Handle(ctx context.Context, e interface{}) error {
	event := e.(*RoomBooked)

	return b.readModelBuilder.buildBookingsReadModel(event.GuestName)
}

type SpecialBookingsFinancialReport struct {
	readModelBuilder readModelBuilder
}

func (b SpecialBookingsFinancialReport) HandlerName() string {
	return "SpecialBookingsFinancialReport"
}

func (SpecialBookingsFinancialReport) NewEvent() interface{} {
	return &SpecialRoomBooked{}
}

func (b *SpecialBookingsFinancialReport) Handle(ctx context.Context, e interface{}) error {
	event := e.(*SpecialRoomBooked)

	return b.readModelBuilder.buildBookingsReadModel(event.VIPGuestName)
}
```
In that case, EventHandler is just calling something which is responsible for building read models (also, Single Responsibility Principle will be satisfied here :)). 

did it help? :)

**Comment by roblaszczak** [comment]
I hope this is clean. If not - please let us know :)
