### ISSUE TITLE
Add github discussions

### ISSUE THREAD

**Issue by jrschumacher** [ThreeDotsLabs/watermill#499]
Since there are many different ways to utilize watermill to solve various problems I think the project could benefit from a Discussions. For instance I was interested in how others have solved the cron and scheduled issue and there is a issue available, but its closed so GitHub's UX doesn't encourage discovery.

If it were a discussion with many threads there could be many different ideas shared and engagement could happen with depth.

**Comment by m110** [comment]
Thanks for the @jrschumacher, let's give it a try! 🚀
