### ISSUE TITLE
SMTP-based MQ engine

### ISSUE THREAD

**Issue by shah** [ThreeDotsLabs/watermill#81]
I was looking for an SMTP-based MQ pub/sub capability: basically using gmail or any other SMTP provider as a "poor man's" MQ for small number of messages. Has anyone seen such a system that can be wrapped as a Watermill component?

**Comment by roblaszczak** [comment]
Hello, I think that it is possible to implement it :) If you want to experiment a bit with it you can start with this page: https://watermill.io/docs/pub-sub-implementing/ If you need any help, please ask!

**Comment by shah** [comment]
Thanks @roblaszczak. I wonder if you know anyone in the Watermill community I can hire to build a PubSub engine for the [GMail golang API](https://developers.google.com/gmail/api/quickstart/go). What I'd like to do is to use GMail as a low-traffic MQ :-)

**Comment by roblaszczak** [comment]
@m110 @maclav3 ? :) but we are now mostly focused on releasing v1.0 so it may be hard. The question is what do you need to particularly have SMTP based queue, or some SQL (MySQL, Postgres?) base Pub Sub will be also acceptable? I'm asking because SQL databases are also commonly available and we will add SQL based PubSub with v1.0 release.

**Comment by shah** [comment]
We're planning on using gmail for MQ because we need some manual intervention with certain messages (tagging, deleting, etc.) and that's easy to do since there's a UI available in gmail that non-technical users can use with ease. With any other MQ store we'd need to create an admin UI.

**Comment by roblaszczak** [comment]
Unfortunately, it's pretty unlikely that we will have time to push it forward. In theory, it is possible to implement it but our recommendation is to use more traditional Queue or Pub/Sub :)
